Repository ServiceInnovationLab/FamilyServiceDirectorySearchinator, pull requests merged in 2018-02, with the labels that each got.

#49 Continuous deployment
  .travis.yml
Labels: in progress

#50 BUGFIX: Fix our continuous deployment
  scripts/deploy.sh
Labels: bug, in progress

#47 Feature/styles
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/__tests__/App.js
  src/__tests__/App.test.js
  src/__tests__/FilterButton.test.js
  src/__tests__/Service.test.js
  src/components/App.js
  src/components/FilterButton.js
  src/components/Info.js
  src/components/SearchFilters.js
  src/components/SearchForm.js
  src/components/SearchResults.js
  src/components/Service.js
  src/components/ServiceMapMarker.js
  src/index.js
  src/styles/Form.css
  src/styles/Form.css.map
  src/styles/Nav.css
  src/styles/Nav.css.map
  src/styles/SearchResults.css
  src/styles/SearchResults.css.map
  src/styles/helpers/lists.css
  src/styles/helpers/lists.css.map
  src/styles/index.css
  src/styles/scss/Form.scss
  src/styles/scss/Nav.scss
  src/styles/scss/SearchResults.scss
  src/styles/scss/helpers/lists.scss
Labels: in progress

#67 Object Error
  src/components/FilterButton.js
  src/components/Info.js
  src/components/ServiceMapMarker.js
Labels: in progress

#69 Add back travis deploy script
  .travis.yml
Labels: in progress

#72 Adding scss lint config file, and hound
  .hound.yml
  .scss-lint.yml
Labels: in progress

#73 Feature/pull request template
  PULL_REQUEST_TEMPLATE
Labels: chore, enhancement, in progress

#75 Auto corrected by following semi
  src/__tests__/Address.test.js
  src/__tests__/FilterButton.test.js
  src/components/Info.js
  src/components/Service.js
Labels: in progress

#74 Fix/permalinks
  .eslintrc
  FamilyServiceDirectorySearchinator/asset-manifest.json
  FamilyServiceDirectorySearchinator/favicon.ico
  FamilyServiceDirectorySearchinator/index.html
  FamilyServiceDirectorySearchinator/manifest.json
  FamilyServiceDirectorySearchinator/service-worker.js
  FamilyServiceDirectorySearchinator/static/css/main.588f1a39.css
  FamilyServiceDirectorySearchinator/static/css/main.588f1a39.css.map
  FamilyServiceDirectorySearchinator/static/js/main.cab1d7c1.js
  FamilyServiceDirectorySearchinator/static/js/main.cab1d7c1.js.map
  development.env
  package.json
  production.env
  public/index.html
  src/__tests__/Address.test.js
  src/__tests__/App.test.js
  src/__tests__/FilterButton.test.js
  src/__tests__/Redux.test.js
  src/actions/index.js
  src/components/Address.js
  src/components/AddressResolver.js
  src/components/App.js
  src/components/FilterButton.js
  src/components/Forms/AddressField.js
  src/components/Info.js
  src/components/Map/MapResults.js
  src/components/Map/ServiceMapMarker.js
  src/components/SearchFilters.js
  src/components/SearchForm.js
  src/components/SearchResults.js
  src/components/Service.js
  src/components/Service/Filters.js
  src/components/Service/Service.js
  src/components/Service/ServiceInfo.js
  src/components/ServiceMapMarker.js
  src/container/app-container.js
  src/index.js
  src/reducers/index.js
  src/styles/Form.css
  src/styles/Form.css.map
  src/styles/Nav.css
  src/styles/Nav.css.map
  src/styles/SearchResults.css
  src/styles/SearchResults.css.map
  src/styles/Service.css
  src/styles/Service.css.map
  src/styles/scss/Form.scss
  src/styles/scss/Nav.scss
  src/styles/scss/Service.scss
  src/styles/scss/variables.scss
  src/styles/variables.css
  src/styles/variables.css.map
Labels: in progress
